name: Test Dispatch

on:
  push:
    tags:
      - 'v*'
  # Add manual trigger for testing
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to simulate (e.g., v1.2.3 or v1.2.3-rc1)'
        required: true
        default: 'v1.0.0'

jobs:
  test-dispatch-chart-release:
    permissions:
      contents: read
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Set tag name
        id: set-tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag_name=${{ github.event.inputs.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Test Dispatch to rancher/charts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use regular GitHub token instead of App token
        run: |
          TAG_NAME="${{ steps.set-tag.outputs.tag_name }}"
          echo "Testing dispatch with tag: $TAG_NAME"
          
          # Determine version override based on tag
          VERSION_OVERRIDE="minor"
          if [[ "$TAG_NAME" == *"-rc"* ]]; then
            VERSION_OVERRIDE="auto"
          fi
          
          echo "Version override: $VERSION_OVERRIDE"
          echo "Would dispatch to rancher/charts with:"
          echo "  - Repository: rancher/charts"
          echo "  - Branch: dev-v2.12"
          echo "  - Chart: rancher-gke-operator"
          echo "  - Version Override: $VERSION_OVERRIDE"
          
          # For testing, let's try to dispatch to your forked charts repo
          # Replace 'your-username' with your actual GitHub username
          CHARTS_REPO="swastik959/charts"  # Change this to your fork
          
          echo "Attempting to dispatch to $CHARTS_REPO..."
          
          # Check if the workflow exists in your forked repo
          if gh workflow list --repo "$CHARTS_REPO" | grep -q "Manual Trigger for Auto Bump"; then
            echo "Found 'Manual Trigger for Auto Bump' workflow in $CHARTS_REPO"
            
            gh workflow run "Manual Trigger for Auto Bump" \
              --repo "$CHARTS_REPO" \
              --ref dev-v2.12 \
              -F chart=rancher-aks-operator \
              -F branch=dev-v2.12 \
              -F version-override=$VERSION_OVERRIDE
              
            echo "Dispatch successful!"
          else
            echo "Workflow 'Manual Trigger for Auto Bump' not found in $CHARTS_REPO"
            echo "Available workflows:"
            gh workflow list --repo "$CHARTS_REPO" || echo "Could not list workflows (check if repo exists and is accessible)"
          fi